### ISSUE TITLE
Errors when trying to run buildout

### ISSUE THREAD

**Issue by skotechaeng** [ENCODE-DCC/encoded#3079]
I am experiencing the following errors when trying to run buildout.  Appreciate any thoughts on this:

$ bin/buildout
mr.developer: Queued 'snovault' for checkout.
mr.developer: Skipped checkout of existing package 'snovault'.
Develop: '/home/encoded/encoded/.'
Develop: '/home/encoded/encoded/develop/snovault'
warning: no files found matching '*.md'
Updating _mr.developer.
Installing encoded.
Getting distribution for 'cryptacular==1.4.1'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from cryptacular/bcrypt/_bcrypt.c:26:
crypt_blowfish-1.2/crypt.h:17:10: fatal error: gnu-crypt.h: No such file or directory
 #include <gnu-crypt.h>
          ^~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install /tmp/tmpwqc8and9get_dist/cryptacular-1.4.1.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing encoded.
  Getting distribution for 'cryptacular==1.4.1'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/encoded/encoded/eggs/zc.recipe.egg-2.0.4-py3.6.egg/zc/recipe/egg/egg.py", line 193, in install
    reqs, ws = self.working_set()
  File "/home/encoded/encoded/eggs/zc.recipe.egg-2.0.4-py3.6.egg/zc/recipe/egg/egg.py", line 82, in working_set
    allow_hosts=self.allow_hosts,
  File "/home/encoded/encoded/eggs/zc.recipe.egg-2.0.4-py3.6.egg/zc/recipe/egg/egg.py", line 135, in _working_set
    allow_hosts=allow_hosts)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)

**Comment by hitz** [comment]
What branch are you using?   I think something cropped up recently with a dependency of a dependency.  Try the dev branch or v94.0 release tag.  (We don't always synch master).

**Comment by skotechaeng** [comment]
Thanks for the quick response.  I tried the dev branch and got these errors.  I then tried the ENCD-3983-update-to-ubuntu-18 branch but I got the following:

WARNING: The easy_install command is deprecated and will be removed in a future version.
build/temp.linux-x86_64-3.6/check_libyaml.c:2:10: fatal error: yaml.h: No such file or directory
 #include <yaml.h>
          ^~~~~~~~
compilation terminated.

Installing npm-install.
/tmp/tmp_piswll0/run: 1: /tmp/tmp_piswll0/run: npm: not found
While:
  Installing npm-install.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/lib/python3.6/dist-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.6.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.6.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.6.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sh /tmp/tmp_piswll0/run' returned non-zero exit status 127.

I'll try v94.0 and report back.

**Comment by hitz** [comment]
hmm dev==v94 so that won't help.  This is on a mac or linux machine?

**Comment by hitz** [comment]
OH.  encoded doesn't (yet) work under python 3.6.  We are working on that, probably be ready early 2020.  You can use pyenv to install 3.4.3; that is currently what we support (versions of 3.5 on a mac have been known to work, but not 3.6 or 3.7 yet)

**Comment by skotechaeng** [comment]
I tried on Mac and Ubuntu.  Ahhh good to know it doesn't work on 3.6 :-)  It's what I am using.  I'll make the change.

**Comment by skotechaeng** [comment]
I have Python 3.4.3, but I am still getting the following.  Appreciate any other input on this.  I am using the Dev branch.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python3.4/dist-packages/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/lib/python3.4/dist-packages/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.4.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.4.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/home/encoded/encoded/eggs/collective.recipe.cmd-0.11-py3.4.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sh /tmp/tmpw0c0n35t/run' returned non-zero exit status 1

**Comment by hitz** [comment]
What version of node do you have?  Sometimes our README gets out of date w.r.t. new macs.  I just got a new one, so I will try to find some time to run through and check it in the next day or so...

**Comment by skotechaeng** [comment]
Thanks so much. I am running v0.10.48 on Ubuntu.

**Comment by hitz** [comment]
What version of Ubuntu?  We don't usually install the dev version there.   It runs the production version though, so it should theoretically work.

**Comment by skotechaeng** [comment]
Ubuntu 14.04.

**Comment by hitz** [comment]
that's the correct version; we just don't run the local install on linux very often.  I know it works, but sometimes packages drift.

**Comment by hitz** [comment]
production install is a little different we do that all the time; if you want to, you can poke around in the cloud-config.yml but they are large.

**Comment by caseylitton** [comment]
You'll want to upgrade pip and setuptools prior to installing any other pip packages.  That could be an issue.  

pip install --upgrade pip setuptools

This is a good thing to do on whenever you start using a new python env.  Also make sure all the apt-get packages were install properly.  

There are permission issues I've run into when installing some pip packages.  You can install with sudo for development.   But I would not do this with a production environment.

**Comment by hitz** [comment]
if that doesn't work... one of our forkers has a readme: https://github.com/utsw-bicf/pandiseased/blob/kce/UbuntuEnvironmentSetup.md

**Comment by skotechaeng** [comment]
Thanks so much!  So I have been pretty much running cloud-config.yaml, but gleaning from it manually so I can catch any errors and also learn along the way.  I will try the forkers readme and see how it goes.  I will also try pip and setup tools before any other packages.

**Comment by skotechaeng** [comment]
Back to it after Xmas break.  I got past the issue.  The npm install from the forkers readme is what I needed.  I also had some permissions issues in the encoded home directory.  Finally I had to issue "git config --global url."https://".insteadOf git://" because we cannot get to git://github.com/VALIS-software/valis-hpgv.git from out network.  At some point the buildout run git ls-remote -h -t git://github.com/VALIS-software/valis-hpgv.git and it was getting stuck there.  By the way I am doing this on Azure, so I am creating this step by step rather than using the AWS yaml.  I am going to proceed with the rest of the steps, but I am going to close this issue.  Thanks for getting me past it.

**Comment by vsmalladi** [comment]
@skotechaeng I am also looking into putting this on Azure. If you can share your information that would be great.

**Comment by skotechaeng** [comment]
@vsmalladi, I will be more than happy to share the information :-).  Ideally I would like to contribute back to this project by providing yaml/sh scripts to run in Azure.  For now doing it manually and trying to make it work.

**Comment by skotechaeng** [comment]
@vsmalladi I have got this running in Azure.  Once my notes are cleaned up, I will send them to you.  For now I have development running, but will run production soon.
